name: "GreenPulse"
version: "0.1.13"
slug: "greenpulse"
description: "Intelligent irrigation planner with OpenWeatherMap integration and local database"
url: "https://github.com/vinczem/greenpulse"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
map:
  - config:rw
  - share:rw
options:

  openweathermap_api_key: ""
  latitude: 0.0
  longitude: 0.0
  pump_capacity_lpm2: 10.0
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic_command: "greenpulse/command"
  mqtt_topic_heartbeat: "greenpulse/heartbeat"
  mqtt_topic_feedback: "greenpulse/feedback"
  weather_update_interval_min: 60
  log_level: "info"
  force_daily_watering: false
  force_watering_minutes: 15
  grass_type: "Univerzális keverék"
  soil_type: "Vályog"
  shade_percentage: 0
  min_watering_amount: 5
  max_watering_amount: 25
schema:
  openweathermap_api_key: str
  latitude: float
  longitude: float
  pump_capacity_lpm2: float
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic_command: str
  mqtt_topic_heartbeat: str
  mqtt_topic_feedback: str
  weather_update_interval_min: int
  log_level: list(debug|info|warning|error|critical)
  force_daily_watering: bool
  force_watering_minutes: int
  grass_type: list(Univerzális keverék|Sportfű|Ornamentális|Szárazságtűrő|Egyéb)
  soil_type: list(Agyagos|Homokos|Vályog|Humuszos|Ismeretlen)
  shade_percentage: int(0,100)
  min_watering_amount: float
  max_watering_amount: float
ports:
  8088/tcp: 8088
  8081/tcp: 8081
ports_description:
  8088/tcp: Web Interface
  8081/tcp: phpMyAdmin
ingress: true
ingress_port: 8088
